version: "3.2"

services:
  php:
    build:
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "127.0.0.1:9657:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
      - ./apache/demo.virtualhost.conf:/usr/local/apache2/conf/demo.apache.conf:ro
    container_name: apache
  mysql:
    image: mariadb
    volumes:
            - ./mariadb/mariadb_data:/var/lib/mysql
            - ./mariadb/team_requete.sql:/docker-entrypoint-initdb.d/team_requete.sql:ro
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
networks:
  frontend:
  backend:
